[build]
  # Change this to the folder where your Vite app actually lives:
  base      = "thecleancreditacademy-frontend"
  command   = "npm install && npm run build"
  publish   = "thecleancreditacademy-frontend/dist"
  functions = "netlify/functions"
