[build]
  # 1️⃣ Change this to the folder where your Vite app really lives
  base      = "thecleancreditacademy-frontend"

  # 2️⃣ How to install & build your front-end
  command   = "npm install && npm run build"

  # 3️⃣ Where the built files end up
  publish   = "thecleancreditacademy-frontend/dist"

  # 4️⃣ Your Netlify Functions folder
  functions = "netlify/functions"


