[build]
  command   = "npm run build"       # uses your package.json “build” script
  publish   = "dist"                # ← point at Vite’s output folder
  functions = "netlify/functions"

[dev]
  command   = "npm run dev"         # only for local netlify dev
  functions = "netlify/functions"

